import Head from 'next/head'

import Header from "../../components/Header";
import {

    TrendingDownIcon,
    TrendingUpIcon,
    TableIcon,
    LightBulbIcon, UserIcon
} from '@heroicons/react/outline'
import {
    HomeIcon,
    MoonIcon,
    CogIcon,
    AcademicCapIcon,
    ShoppingCartIcon,
    DocumentTextIcon, BellIcon, SearchIcon, ArrowRightIcon
} from '@heroicons/react/solid'

import {TitleCard} from "../../components/section-title";
import LineChart from "../../components/Dashboard/Charts/Lines";
import Dotnut from "../../components/Dashboard/Charts/Doughnut";
import Transactions from "../../components/Dashboard/Transactions";
import {Field} from "../../components/Elements/Field";
import {useForm} from "react-hook-form";
import Button from "../../components/Elements/Button";
export default function Dashboard() {


    const { register, handleSubmit, formState: { errors } } = useForm();
    const onSubmit = data => {
        console.log(data)
    };


    return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <div className="w-full">
            <div className="flex h-screen">
                {/*Middle Section*/}
                <div className="lg:w-2/3 my-5 px-2 py-2 mx-auto overflow-y-auto">
                    <Header />
                       {/*Rapid Access*/}
                    <div className="my-10">
                        <TitleCard title="Mes accés rapides" />
                        <div className="w-full flex flex-row justify-between">
                            <div className="flex flex-col items-center justify-center border-gray-50 h-20 w-20 bg-yellow-500 bg-opacity-5 rounded-lg cursor-pointer transition duration-700 hover:shadow-md">
                                <HomeIcon className="h-5 w-5 text-yellow-600 mb-2"/>
                                <div className="text-xs text-yellow-600">Immobilier</div>
                            </div>
                            <div className="flex flex-col items-center justify-center border-gray-50 h-20 w-20 bg-blue-500 bg-opacity-5 rounded-lg cursor-pointer transition duration-700 hover:shadow-md">
                                <ShoppingCartIcon className="h-5 w-5 text-blue-600 mb-2"/>
                                <div className="text-xs text-blue-600">Shopping</div>
                            </div>
                            <div className="flex flex-col items-center justify-center border-gray-50 h-20 w-20 bg-red-500 bg-opacity-5 rounded-lg cursor-pointer transition duration-700 hover:shadow-md">
                                <DocumentTextIcon className="h-5 w-5 text-red-600 mb-2"/>
                                <div className="text-xs text-red-600">Factures</div>
                            </div>
                            <div className="flex flex-col items-center justify-center border-gray-50 h-20 w-20 bg-green-500 bg-opacity-5 rounded-lg cursor-pointer transition duration-700 hover:shadow-md">
                                <AcademicCapIcon className="h-5 w-5 text-green-600 mb-2"/>
                                <div className="text-xs text-green-600">Education</div>
                            </div>
                            <div className="flex flex-col items-center justify-center border-gray-50 h-20 w-20 bg-gray-500 bg-opacity-5 rounded-lg cursor-pointer transition duration-700 hover:shadow-md">
                                <TrendingDownIcon className="h-5 w-5 text-gray-600 mb-2"/>
                                <div className="text-xs text-gray-600">Envoi</div>
                            </div>
                            <div className="flex flex-col items-center justify-center border-gray-50 h-20 w-20 bg-indigo-500 bg-opacity-5 rounded-lg cursor-pointer transition duration-700 hover:shadow-md">
                                <TrendingUpIcon className="h-5 w-5 text-indigo-600 mb-2"/>
                                <div className="text-xs text-indigo-600">Retrait</div>
                            </div>
                            <div className="flex flex-col items-center justify-center border-gray-50 h-20 w-20 bg-purple-500 bg-opacity-5 rounded-lg cursor-pointer transition duration-700 hover:shadow-md">
                                <TableIcon className="h-5 w-5 text-purple-600 mb-2"/>
                                <div className="text-xs text-purple-600">Transactions</div>
                            </div>
                            <div className="flex flex-col items-center justify-center border-gray-50 h-20 w-20 bg-pink-500 bg-opacity-5 rounded-lg cursor-pointer transition duration-700 hover:shadow-md">
                                <LightBulbIcon className="h-5 w-5 text-pink-600 mb-2"/>
                                <div className="text-xs text-pink-600">Comptes</div>
                            </div>
                        </div>
                    </div>
                     {/*LongBar*/}
                    <div className="my-10">
                        <TitleCard title="Résumé" />
                        <div className="shadow-sm bg-gray-50 rounded-md w-full grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4 py-3 px-5 flex justify-between mb-10">
                            <div className="w-full rounded-md p-2">
                                <div className="text-md font-thin text-gray-400 pb-2">Entrée</div>
                                <div className="font-bold text-xl">12 000 000 fcfa</div>
                                <div className="text-yellow-500 font-extrabold">35%</div>
                            </div>
                            <div className=" w-full rounded-md p-2">
                                <div className="w-full rounded-md p-2">
                                    <div className="text-md font-thin text-gray-300">
                                        Sortie
                                    </div>
                                    <div className="font-bold text-xl">12 000 000 fcfa</div>
                                    <div className="text-green-500 font-medium">35%</div>
                                </div>
                            </div>
                            <div className="w-full rounded-md p-2">
                                <div className="w-full rounded-md p-2">
                                    <div className="text-md font-thin text-gray-300">
                                        En attente
                                    </div>
                                    <div className="font-bold text-xl">500 000 fcfa</div>
                                    <div className="text-pink-500 font-medium">5%</div>
                                </div>
                            </div>
                        </div>
                    </div>
                     {/*Charts*/}
                    <div className="my-10">
                        <TitleCard title="Rapports" />
                        <div className="w-full flex flex-row">
                            <div className="w-full lg:w-2/3 sm:w-1/2">
                                <div className="lg:pr-2 bg-white shadow-md rounded-2xl border-gray-100 p-1 lg:m-2">
                                    <LineChart />
                                </div>
                            </div>

                            <div className="w-full lg:w-1/3 sm:w-1/2 lg:m-2">
                                <div className="lg:pr-2 bg-white shadow-md rounded-2xl border-gray-100 p-1 lg:m-2">
                                    <Dotnut />
                                </div>
                            </div>

                        </div>
                    </div>

                </div>


                 {/*Right Section*/}
                <div className="h-screen bg-[#f9f6fb] w-full lg:w-1/3 p-10 border-l border-[#f5f0f0] lg:ml-3 overflow-x-auto">
                        <div className="my-5">
                            <div className="mb-8">
                                <div className="flex justify-center items-center space-x-6">
                                    <div className="flex items-center justify-center  border-gray-50 h-10 w-10 bg-gray-50 rounded-lg shadow-lg cursor-pointer">
                                        <MoonIcon className="h-5 text-purple-900" />
                                    </div>
                                    <div className="flex items-center justify-center border-gray-50 h-10 w-10 bg-gray-50 rounded-lg shadow-lg cursor-pointer">
                                        <CogIcon className="h-5 text-purple-900" />
                                    </div>
                                    <div className="flex relative inline-block items-center justify-center border-gray-50 h-10 w-10 bg-gray-50 rounded-lg shadow-lg cursor-pointer">
                                        <BellIcon className="h-5 text-purple-900" />
                                        <span className="absolute top-0 right-0 inline-flex items-center justify-center px-2 py-1 text-xs font-bold leading-none text-red-100 transform translate-x-1/2 -translate-y-1/2 bg-red-600 rounded-full">
                                            3
                                        </span>
                                    </div>
                                </div>
                            </div>
                            <TitleCard title="Transactions récentes" />
                            <div className="overflow-x-auto py-3">
                                <div className="text-xs text-gray-300 font-normal py-2">Filtrer par :</div>
                                <div className="inline-flex items-center justify-center px-2 py-1 mr-2 bg-purple-900 rounded-full cursor-pointer">
                                    <span className="text-xs font-normal leading-none text-purple-100">Tous</span>
                                </div>
                                <div className="inline-flex items-center justify-center px-2 py-1 mr-2 bg-purple-100 rounded-full cursor-pointer">
                                    <span className="text-xs font-normal leading-none text-purple-700">Immobilier</span>
                                </div>
                                <div className="inline-flex items-center justify-center px-2 py-1 mr-2 bg-purple-100 rounded-full cursor-pointer">
                                    <span className="text-xs font-normal leading-none text-purple-700">Retrait</span>
                                </div>
                                <div className="inline-flex items-center justify-center px-2 py-1 mr-2 bg-purple-100 rounded-full cursor-pointer">
                                    <span className="text-xs font-normal leading-none text-purple-700">Education</span>
                                </div>
                                <div className="inline-flex items-center justify-center px-2 py-1 mr-2 bg-purple-100 rounded-full cursor-pointer">
                                    <span className="text-xs font-normal leading-none text-purple-700">Envoi</span>
                                </div>
                                <div className="inline-flex items-center justify-center px-2 py-1 mr-2 bg-purple-100 rounded-full cursor-pointer">
                                    <span className="text-xs font-normal leading-none text-purple-700">Facture</span>
                                </div>
                                <div className="inline-flex items-center justify-center px-2 py-1 mr-2 bg-purple-100 rounded-full cursor-pointer">
                                    <span className="text-xs font-normal leading-none text-purple-700">Shopping</span>
                                </div>
                            </div>
                            <div className="py-5 overflow-auto h-100">
                                <Transactions />
                            </div>


                            {/*<div className="my-4">
                                <TitleCard title="Envoi rapide" />
                                <form className="p-4 bg-white rounded-md" onSubmit={handleSubmit(onSubmit)}>
                                    <div className="relative">
                                        <Field
                                            {...register("amount", {required: "Le champs est requis"})}
                                            type="text"
                                            name="amount"
                                            error={errors?.amount?.message}
                                            placeholder="Saisir le montant"
                                        />
                                        <Button type="submit" className=" absolute right-0 top-0 mt-4 mr-5">
                                            <ArrowRightIcon className="h-8 w-8 fill-current text-gray-400" />
                                        </Button>
                                    </div>
                                </form>
                            </div>*/}
                        </div>
                </div>


            </div>
        </div>
     {/*  <div className="w-full flex h-screen overflow-y-auto"> */}
          {/* <SideBar /> */}
         {/* <Blocks />*/}
      {/* </div> */}
    </>
  )

}


