export const SET_CONFIG = "SET_CONFIG"

export const SAVE_FIRST_STEP = "SAVE_FIRST_STEP"
export const SAVE_SECOND_STEP = "SAVE_SECOND_STEP"
export const SAVE_THIRD_STEP = "SAVE_THIRD_STEP"
export const SAVE_FOURTH_STEP = "SAVE_FOURTH_STEP"
